"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:52:32.602417+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = spark.read.csv(input_path, header=True, inferSchema=False)
    merchants_df = spark.read.csv(input_path.replace('transactions','merchants'), header=True, inferSchema=False)
    
    # Add metadata columns
    transactions_df = transactions_df.withColumn("ingestion_timestamp", lit(run_date))
    transactions_df = transactions_df.withColumn("source_file", lit("transactions.csv"))
    transactions_df = transactions_df.withColumn("pipeline_run_id", lit(run_id))
    
    # Write as Parquet partitioned by date
    transactions_df.write.mode('overwrite').partitionBy("ingestion_timestamp").parquet(output_path + "/transactions")
    merchants_df.write.mode('overwrite').partitionBy("ingestion_timestamp").parquet(output_path + "/merchants")

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.parquet(bronze_path)
                      .where(col("ingestion_timestamp") == run_date)
                      .cache())
    
    merchants_df = (spark.read.parquet(merchants_path)
                    .where(col("ingestion_timestamp") == run_date)
                     .withColumnRenamed("_c0", "merchant_id")
                    .withColumnRenamed("_c1", "merchant_name")
                    .withColumnRenamed("_c2", "category")
                    .withColumnRenamed("_c3", "city"))
    
    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("amount", col("amount").cast(FloatType()))
    transactions_df = transactions_df.withColumn("transaction_date", col("transaction_date").cast(DateType()))
    transactions_df = transactions_df.withColumn("transaction_id", col("transaction_id").cast(StringType()))
    transactions_df = transactions_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))
    
    # Filter: remove records where transaction_id is NULL or amount < 0
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
    transactions_df = (transactions_df.withColumn("rank", 
                                                  col("ingestion_timestamp").desc_nulls_last())
                       .dropDuplicates(["transaction_id"])
                       .drop("rank"))
    
    # Enrich: join transactions with merchants on merchant_id to get merchant_name, category, city
    enriched_df = (transactions_df.join(broadcast(merchants_df), "merchant_id", "left")
                    .withColumn("quality_flag", 
                                when(col("merchant_id").isNull(), "UNMATCHED").otherwise("CLEAN")))
    
    # Write as Parquet partitioned by date
    enriched_df.write.mode('overwrite').partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    input_path = "s3://your-bucket/bronze/"
    bronze_path = "s3://your-bucket/silver/"
    silver_path = "s3://your-bucket/gold/"
    merchants_path = "s3://your-bucket/bronze/merchants/"
    run_date = "2026-05-27"
    run_id = "run_001"
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, bronze_path, merchants_path, silver_path, run_date)
    
    # Write run metadata summary to a JSON file
    run_metadata = {
        "run_date": run_date,
        "run_id": run_id,
        "bronze_ingest_count": spark.read.parquet(bronze_path).count(),
        "silver_transform_count": spark.read.parquet(silver_path).count()
    }
    with open(f"s3://your-bucket/metadata/run_metadata_{run_date}.json", "w") as f:
        json.dump(run_metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, coalesce, avg, collect_set, first, last, mode
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write to Gold layer
    merchant_performance_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Calculate metrics
    customer_ltv_df = silver_df.groupBy("customer_id") \
       .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_spent"),
            count("*").alias("total_txns"),
            avg(col("amount")).alias("avg_txn_value"),
            first("transaction_date").alias("first_txn_date"),
            last("transaction_date").alias("last_txn_date"),
            mode("payment_method").over(Window.partitionBy("customer_id")).alias("preferred_payment_method")
        )
    
    # Write to Gold layer
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id").alias("unique_customers")).alias("unique_customers"),
            count(col("merchant_id").alias("unique_merchants")).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write to Gold layer
    daily_summary_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths
    merchant_performance_output_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_output_path = f"{gold_output_dir}/daily_summary"
    
    # Build Gold layer tables
    build_merchant_performance(spark, silver_path, merchant_performance_output_path, run_date)
    build_customer_ltv(spark, silver_path, customer_ltv_output_path)
    build_daily_summary(spark, silver_path, daily_summary_output_path, run_date)
    
    # Write run metadata summary to JSON
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "tables": [
            {"name": "merchant_performance", "path": merchant_performance_output_path},
            {"name": "customer_ltv", "path": customer_ltv_output_path},
            {"name": "daily_summary", "path": daily_summary_output_path}
        ]
    }
    
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

# Initialize Spark session
spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
